# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-29 20:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cricket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_name', models.CharField(default='', max_length=50)),
                ('on_date', models.DateTimeField(default=datetime.datetime(2017, 3, 30, 2, 6, 33, 91708))),
                ('updated_on', models.DateTimeField(default=datetime.datetime(2017, 3, 30, 2, 6, 33, 91708))),
                ('preview', models.CharField(default='', max_length=200)),
                ('para1', models.CharField(default='', max_length=500)),
                ('para2', models.CharField(default='', max_length=500)),
                ('para3', models.CharField(default='', max_length=500, null=True)),
                ('team1_des', models.CharField(default='', max_length=100, null=True)),
                ('team1', models.CharField(default='', max_length=200)),
                ('team2_des', models.CharField(default='', max_length=100)),
                ('team2', models.CharField(default='', max_length=200)),
                ('team3_des', models.CharField(max_length=100, null=True)),
                ('team3', models.CharField(max_length=200, null=True)),
                ('conclusion', models.CharField(default='', max_length=150)),
                ('final_verdict', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Football',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_name', models.CharField(default='', max_length=50)),
                ('on_date', models.DateTimeField(default=datetime.datetime(2017, 3, 30, 2, 6, 33, 92709))),
                ('updated_on', models.DateTimeField(default=datetime.datetime(2017, 3, 30, 2, 6, 33, 92709))),
                ('preview', models.CharField(default='', max_length=200)),
                ('para1', models.CharField(default='', max_length=500)),
                ('para2', models.CharField(default='', max_length=500)),
                ('para3', models.CharField(default='', max_length=500, null=True)),
                ('team1_des', models.CharField(default='', max_length=100, null=True)),
                ('team1', models.CharField(default='', max_length=200)),
                ('team2_des', models.CharField(default='', max_length=100)),
                ('team2', models.CharField(default='', max_length=200)),
                ('team3_des', models.CharField(max_length=100, null=True)),
                ('team3', models.CharField(max_length=200, null=True)),
                ('conclusion', models.CharField(default='', max_length=150)),
                ('final_verdict', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
