# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-29 20:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cricket',
            name='on_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 30, 2, 6, 54, 587408)),
        ),
        migrations.AlterField(
            model_name='cricket',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 30, 2, 6, 54, 587408)),
        ),
        migrations.AlterField(
            model_name='football',
            name='on_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 30, 2, 6, 54, 588391)),
        ),
        migrations.AlterField(
            model_name='football',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 30, 2, 6, 54, 588391)),
        ),
    ]
