# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-31 11:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasyapp', '0002_auto_20170330_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='cricket',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='football',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='cricket',
            name='on_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 31, 16, 34, 41, 22579)),
        ),
        migrations.AlterField(
            model_name='cricket',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 31, 16, 34, 41, 22579)),
        ),
        migrations.AlterField(
            model_name='football',
            name='on_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 31, 16, 34, 41, 23580)),
        ),
        migrations.AlterField(
            model_name='football',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 31, 16, 34, 41, 23580)),
        ),
    ]
