# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-31 11:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasyapp', '0003_auto_20170331_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cricket',
            old_name='match_name',
            new_name='cricket_match_name',
        ),
        migrations.RenameField(
            model_name='football',
            old_name='match_name',
            new_name='football_match_name',
        ),
        migrations.AlterField(
            model_name='cricket',
            name='on_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 31, 16, 39, 40, 256483)),
        ),
        migrations.AlterField(
            model_name='cricket',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 31, 16, 39, 40, 256483)),
        ),
        migrations.AlterField(
            model_name='football',
            name='on_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 31, 16, 39, 40, 257986)),
        ),
        migrations.AlterField(
            model_name='football',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 31, 16, 39, 40, 257986)),
        ),
    ]
