# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-02 06:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasyapp', '0004_auto_20170331_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(max_length=100)),
                ('is_cricket', models.BooleanField(default=False)),
                ('is_football', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='football',
            name='on_date',
        ),
        migrations.AlterField(
            model_name='cricket',
            name='conclusion',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='cricket',
            name='final_verdict',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='cricket',
            name='on_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cricket',
            name='para1',
            field=models.CharField(default='', max_length=700),
        ),
        migrations.AlterField(
            model_name='cricket',
            name='para2',
            field=models.CharField(default='', max_length=700),
        ),
        migrations.AlterField(
            model_name='cricket',
            name='para3',
            field=models.CharField(default='', max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='cricket',
            name='preview',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='cricket',
            name='team1',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='cricket',
            name='team1_des',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='cricket',
            name='team2',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='cricket',
            name='team2_des',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='cricket',
            name='team3',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cricket',
            name='team3_des',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='cricket',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 2, 12, 27, 31, 208571)),
        ),
        migrations.AlterField(
            model_name='football',
            name='conclusion',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='football',
            name='final_verdict',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='football',
            name='para1',
            field=models.CharField(default='', max_length=700),
        ),
        migrations.AlterField(
            model_name='football',
            name='para2',
            field=models.CharField(default='', max_length=700),
        ),
        migrations.AlterField(
            model_name='football',
            name='para3',
            field=models.CharField(default='', max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='football',
            name='preview',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='football',
            name='team1',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='football',
            name='team1_des',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='football',
            name='team2',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='football',
            name='team2_des',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='football',
            name='team3',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='football',
            name='team3_des',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='football',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 2, 12, 27, 31, 210072)),
        ),
        migrations.AddField(
            model_name='cricket',
            name='tournament',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fantasyapp.Tournament'),
        ),
        migrations.AddField(
            model_name='football',
            name='tournament',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fantasyapp.Tournament'),
        ),
    ]
