# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-02 07:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasyapp', '0005_auto_20170402_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 2, 12, 31, 23, 801617)),
        ),
        migrations.AlterField(
            model_name='cricket',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 2, 12, 31, 23, 802617)),
        ),
        migrations.AlterField(
            model_name='football',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 2, 12, 31, 23, 804619)),
        ),
    ]
