# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-02 07:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasyapp', '0006_auto_20170402_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='football',
            name='on_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 2, 13, 19, 53, 499705)),
        ),
        migrations.AlterField(
            model_name='cricket',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 2, 13, 19, 53, 498205)),
        ),
        migrations.AlterField(
            model_name='football',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 2, 13, 19, 53, 499705)),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 2, 13, 19, 53, 497703)),
        ),
    ]
